on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

name: Build and push Docker images
  uses: docker/build-push-action@v1
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    repository: macsstacks/etcd-docker
    tag_with_ref: true
    tag_with_sha: true